CREATE TABLE IF NOT EXISTS productos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL,
  nombre VARCHAR(255) NOT NULL
);

INSERT INTO productos (codigo, nombre) VALUES ('50010', 'Impuesto 7/2022');
INSERT INTO productos (codigo, nombre) VALUES ('101000', 'Taco Carne');
INSERT INTO productos (codigo, nombre) VALUES ('101001', 'Taco P.Pic');
INSERT INTO productos (codigo, nombre) VALUES ('101002', 'Taco Pollo Asado');
INSERT INTO productos (codigo, nombre) VALUES ('101005', 'Taco Veg');
INSERT INTO productos (codigo, nombre) VALUES ('101100', 'Taco Sup P.Pic');
INSERT INTO productos (codigo, nombre) VALUES ('101101', 'Taco Sup Carne');
INSERT INTO productos (codigo, nombre) VALUES ('101103', 'Taco Sup Pollo Asado 3.00');
INSERT INTO productos (codigo, nombre) VALUES ('101200', 'SoftTaco Carne');
INSERT INTO productos (codigo, nombre) VALUES ('101203', 'SoftTaco Pollo Asado 2.00');
INSERT INTO productos (codigo, nombre) VALUES ('101215', 'Chicken Taco');
INSERT INTO productos (codigo, nombre) VALUES ('101300', 'SftTA Sup Carne');
INSERT INTO productos (codigo, nombre) VALUES ('101301', 'SftTA Sup P.Pic');
INSERT INTO productos (codigo, nombre) VALUES ('101302', 'SftTA Sup Pollo Asado 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('102010', 'Burrito Carne&Patatas 3.00');
INSERT INTO productos (codigo, nombre) VALUES ('102016', 'Chicken Burrito');
INSERT INTO productos (codigo, nombre) VALUES ('102019', 'Burrito Cheesy Carne 14.00');
INSERT INTO productos (codigo, nombre) VALUES ('102020', 'GRI BBQ Carne');
INSERT INTO productos (codigo, nombre) VALUES ('102025', 'BU San Diego Carne 4.00');
INSERT INTO productos (codigo, nombre) VALUES ('102039', 'BFR BBQ Carne');
INSERT INTO productos (codigo, nombre) VALUES ('102050', 'Cheesy Burr Veg');
INSERT INTO productos (codigo, nombre) VALUES ('102059', 'BU San Diego Veg');
INSERT INTO productos (codigo, nombre) VALUES ('102114', 'Cheesy Burr P Pic');
INSERT INTO productos (codigo, nombre) VALUES ('102117', 'BU San Diego Pollo Asado 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('102136', 'GRI BBQ 1Pollo');
INSERT INTO productos (codigo, nombre) VALUES ('102138', 'BFR BBQ 1Pollo');
INSERT INTO productos (codigo, nombre) VALUES ('103000', 'Gran Burrito Pollo Asado 2.00');
INSERT INTO productos (codigo, nombre) VALUES ('103002', 'Gran Burrito Carne 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('103003', 'Gran Burrito P.Pic 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('103005', 'Gran Burrito Veggie 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('103101', 'Twin BC Pollo Asado 2.00');
INSERT INTO productos (codigo, nombre) VALUES ('103401', 'Quesarito Carne');
INSERT INTO productos (codigo, nombre) VALUES ('103402', 'Quesarito Pollo Asado 3.00');
INSERT INTO productos (codigo, nombre) VALUES ('103409', 'Quesarito P.Pic');
INSERT INTO productos (codigo, nombre) VALUES ('103411', 'Quesarito Veg');
INSERT INTO productos (codigo, nombre) VALUES ('104002', 'Cr Wrap Carne');
INSERT INTO productos (codigo, nombre) VALUES ('104003', 'Cr Wrap P Pic');
INSERT INTO productos (codigo, nombre) VALUES ('104005', 'Cr Wrap Pollo Asado 2.00');
INSERT INTO productos (codigo, nombre) VALUES ('104012', 'Wrap Slider Carne');
INSERT INTO productos (codigo, nombre) VALUES ('104049', 'Cr Wrap BC Carne');
INSERT INTO productos (codigo, nombre) VALUES ('104100', 'Quesadilla Pollo Asado 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('104102', 'Quesadilla Queso');
INSERT INTO productos (codigo, nombre) VALUES ('104103', 'Quesadilla P.Pic');
INSERT INTO productos (codigo, nombre) VALUES ('104104', 'Quesadilla Carne');
INSERT INTO productos (codigo, nombre) VALUES ('104118', 'Quesadilla Veg');
INSERT INTO productos (codigo, nombre) VALUES ('104121', 'Bacon CH QU Carne');
INSERT INTO productos (codigo, nombre) VALUES ('104133', 'Burrito BC');
INSERT INTO productos (codigo, nombre) VALUES ('104142', 'Mini Quesadilla Carne 3.00');
INSERT INTO productos (codigo, nombre) VALUES ('104143', 'Mini Quesadilla Pollo 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('104144', 'Mini Quesadilla P.Pic 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('104200', 'Kidsadilla Queso');
INSERT INTO productos (codigo, nombre) VALUES ('104205', 'Kidsadilla Jamon');
INSERT INTO productos (codigo, nombre) VALUES ('105000', 'Nachos P');
INSERT INTO productos (codigo, nombre) VALUES ('105013', 'NaBell Gr Carne');
INSERT INTO productos (codigo, nombre) VALUES ('105050', 'Patatas Fritas P');
INSERT INTO productos (codigo, nombre) VALUES ('105057', 'Patatas Fritas P');
INSERT INTO productos (codigo, nombre) VALUES ('105080', 'Patatas Fritas M');
INSERT INTO productos (codigo, nombre) VALUES ('105081', 'Nachos M');
INSERT INTO productos (codigo, nombre) VALUES ('105082', 'Patatas Kid');
INSERT INTO productos (codigo, nombre) VALUES ('105084', 'Nachos Supreme');
INSERT INTO productos (codigo, nombre) VALUES ('105091', 'Mex Nachos M');
INSERT INTO productos (codigo, nombre) VALUES ('105102', 'Guacamole');
INSERT INTO productos (codigo, nombre) VALUES ('105108', 'Salsa Nacho');
INSERT INTO productos (codigo, nombre) VALUES ('105113', 'Crema Agria');
INSERT INTO productos (codigo, nombre) VALUES ('105117', 'Qso roll up Carne');
INSERT INTO productos (codigo, nombre) VALUES ('105121', 'Patatas Fritas G');
INSERT INTO productos (codigo, nombre) VALUES ('105122', 'Nachos G');
INSERT INTO productos (codigo, nombre) VALUES ('105123', 'Cheese Snack Carne 5.00');
INSERT INTO productos (codigo, nombre) VALUES ('105126', 'Chicken Nacho 9');
INSERT INTO productos (codigo, nombre) VALUES ('105132', 'Barbacoa');
INSERT INTO productos (codigo, nombre) VALUES ('105133', 'Bacon TopFries');
INSERT INTO productos (codigo, nombre) VALUES ('105134', 'Patatas Fritas XG');
INSERT INTO productos (codigo, nombre) VALUES ('105143', 'Salsa Mild');
INSERT INTO productos (codigo, nombre) VALUES ('105145', 'Salsa Fire');
INSERT INTO productos (codigo, nombre) VALUES ('105146', 'SIN Salsa');
INSERT INTO productos (codigo, nombre) VALUES ('105164', 'SIN Extra Salsa');
INSERT INTO productos (codigo, nombre) VALUES ('105170', 'Patatas Fritas Premium M 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('105171', 'Patatas Fritas Premium G 2.00');
INSERT INTO productos (codigo, nombre) VALUES ('105172', 'Patatas Fritas Premium XG 2.00');
INSERT INTO productos (codigo, nombre) VALUES ('105173', 'Chicken Nacho 3');
INSERT INTO productos (codigo, nombre) VALUES ('106002', 'Ensalada M');
INSERT INTO productos (codigo, nombre) VALUES ('106005', 'EN Ens Pollo Asado 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('106006', 'Ensalada..');
INSERT INTO productos (codigo, nombre) VALUES ('106012', 'BU Bowl Mexican P Pic 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('107000', 'Cono Bell');
INSERT INTO productos (codigo, nombre) VALUES ('107009', 'Danonino');
INSERT INTO productos (codigo, nombre) VALUES ('107010', 'ChocoBall');
INSERT INTO productos (codigo, nombre) VALUES ('107017', 'Mini Tarrina de Fresa 3.00');
INSERT INTO productos (codigo, nombre) VALUES ('107018', 'Mini Tarrina de Choc 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('107023', 'Extra Dulce');
INSERT INTO productos (codigo, nombre) VALUES ('107039', 'Kit Kat Chocadilla 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('107065', 'BJ Choco Brownie 100ml 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('107076', 'Postre');
INSERT INTO productos (codigo, nombre) VALUES ('191100', 'Taco Sup P.Pic');
INSERT INTO productos (codigo, nombre) VALUES ('191101', 'Taco Supreme Carne 13.00');
INSERT INTO productos (codigo, nombre) VALUES ('191103', 'Taco Sup P.Asa');
INSERT INTO productos (codigo, nombre) VALUES ('191105', 'Taco Sup Veg');
INSERT INTO productos (codigo, nombre) VALUES ('192016', 'Chicken Burrito');
INSERT INTO productos (codigo, nombre) VALUES ('193401', 'Quesarito C.Pic');
INSERT INTO productos (codigo, nombre) VALUES ('194002', 'Cr Wrap Carne');
INSERT INTO productos (codigo, nombre) VALUES ('195000', 'Nachos P');
INSERT INTO productos (codigo, nombre) VALUES ('195050', 'Patatas Fritas P');
INSERT INTO productos (codigo, nombre) VALUES ('195080', 'Patatas Fritas M');
INSERT INTO productos (codigo, nombre) VALUES ('195084', 'Nachos Supreme');
INSERT INTO productos (codigo, nombre) VALUES ('195108', 'Salsa Nacho');
INSERT INTO productos (codigo, nombre) VALUES ('195113', 'Nata Agria');
INSERT INTO productos (codigo, nombre) VALUES ('195116', 'Salsa Mexican');
INSERT INTO productos (codigo, nombre) VALUES ('195120', 'Chicken Nacho 6');
INSERT INTO productos (codigo, nombre) VALUES ('195121', 'Patatas Fritas G');
INSERT INTO productos (codigo, nombre) VALUES ('195126', 'Chicken Nacho 9');
INSERT INTO productos (codigo, nombre) VALUES ('197006', 'Tarrina Bell Dul');
INSERT INTO productos (codigo, nombre) VALUES ('197039', 'Kit Kat Chocadilla 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('201001', 'Agua');
INSERT INTO productos (codigo, nombre) VALUES ('201003', 'Lata Cerveza Sin');
INSERT INTO productos (codigo, nombre) VALUES ('201010', 'Cerveza P');
INSERT INTO productos (codigo, nombre) VALUES ('201011', 'Cerveza M');
INSERT INTO productos (codigo, nombre) VALUES ('201019', 'Lata cerveza Classic 3.00');
INSERT INTO productos (codigo, nombre) VALUES ('201021', 'G 22oz');
INSERT INTO productos (codigo, nombre) VALUES ('201022', 'Pet Coca Coca');
INSERT INTO productos (codigo, nombre) VALUES ('201023', 'Pet Coca Zero');
INSERT INTO productos (codigo, nombre) VALUES ('201024', 'Pet Fanta Naranja');
INSERT INTO productos (codigo, nombre) VALUES ('201025', 'Pet Fanta Limon');
INSERT INTO productos (codigo, nombre) VALUES ('201026', 'Pet Fuze Tea');
INSERT INTO productos (codigo, nombre) VALUES ('201028', 'Refresco XG');
INSERT INTO productos (codigo, nombre) VALUES ('201029', 'Agua XG');
INSERT INTO productos (codigo, nombre) VALUES ('201075', 'Coca-Cola M');
INSERT INTO productos (codigo, nombre) VALUES ('201099', 'Fuze Tea M');
INSERT INTO productos (codigo, nombre) VALUES ('201100', 'P 12oz');
INSERT INTO productos (codigo, nombre) VALUES ('201102', 'M 16oz');
INSERT INTO productos (codigo, nombre) VALUES ('201112', 'SIN Bebida');
INSERT INTO productos (codigo, nombre) VALUES ('201130', 'M 16oz');
INSERT INTO productos (codigo, nombre) VALUES ('201160', 'Fuze Tea G');
INSERT INTO productos (codigo, nombre) VALUES ('404001', 'Pollo Asado');
INSERT INTO productos (codigo, nombre) VALUES ('404003', 'Carne Picada');
INSERT INTO productos (codigo, nombre) VALUES ('404004', 'Pollo Picante');
INSERT INTO productos (codigo, nombre) VALUES ('404010', 'Bacon');
INSERT INTO productos (codigo, nombre) VALUES ('404019', 'Pollo Asado');
INSERT INTO productos (codigo, nombre) VALUES ('404020', 'Carne Picada 2');
INSERT INTO productos (codigo, nombre) VALUES ('404021', 'Pollo Picante');
INSERT INTO productos (codigo, nombre) VALUES ('404026', 'Pollo Crujiente');
INSERT INTO productos (codigo, nombre) VALUES ('404101', 'Salsa Nacho');
INSERT INTO productos (codigo, nombre) VALUES ('404201', 'Lechuga');
INSERT INTO productos (codigo, nombre) VALUES ('404202', 'Tomate');
INSERT INTO productos (codigo, nombre) VALUES ('404203', 'Pico de Gallo');
INSERT INTO productos (codigo, nombre) VALUES ('404300', 'Queso Cheddar');
INSERT INTO productos (codigo, nombre) VALUES ('404301', 'Doble Queso');
INSERT INTO productos (codigo, nombre) VALUES ('404400', 'Guacamole');
INSERT INTO productos (codigo, nombre) VALUES ('404401', 'Nata Agria');
INSERT INTO productos (codigo, nombre) VALUES ('404403', 'Salsa CreamyJalape�o 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('404412', 'Salsa Barbacoa');
INSERT INTO productos (codigo, nombre) VALUES ('404414', 'Salsa Habanero');
INSERT INTO productos (codigo, nombre) VALUES ('404428', 'Pollo Crujiente');
INSERT INTO productos (codigo, nombre) VALUES ('404436', 'Guacamole pico de gallo 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('414007', 'SIN Salsa Haban');
INSERT INTO productos (codigo, nombre) VALUES ('414020', 'SIN Salsa Nacho');
INSERT INTO productos (codigo, nombre) VALUES ('414022', 'SIN Lechuga');
INSERT INTO productos (codigo, nombre) VALUES ('414023', 'SIN Tomate');
INSERT INTO productos (codigo, nombre) VALUES ('414037', 'SIN Nata Agria');
INSERT INTO productos (codigo, nombre) VALUES ('501010', 'M Quesadilla');
INSERT INTO productos (codigo, nombre) VALUES ('501079', 'M Crunchy Wrap BC');
INSERT INTO productos (codigo, nombre) VALUES ('501186', 'Kids Nuevo');
INSERT INTO productos (codigo, nombre) VALUES ('501224', 'Taco Tuesday');
INSERT INTO productos (codigo, nombre) VALUES ('501275', 'M Chicken BU');
INSERT INTO productos (codigo, nombre) VALUES ('502077', 'M CWrap');
INSERT INTO productos (codigo, nombre) VALUES ('502078', 'M Quesadilla');
INSERT INTO productos (codigo, nombre) VALUES ('502079', 'M CHicken BU');
INSERT INTO productos (codigo, nombre) VALUES ('502080', 'M Quesarito');
INSERT INTO productos (codigo, nombre) VALUES ('502081', 'M Gran Burrito');
INSERT INTO productos (codigo, nombre) VALUES ('502083', 'M BU Bowl Mexican');
INSERT INTO productos (codigo, nombre) VALUES ('502085', 'M BIGC IND');
INSERT INTO productos (codigo, nombre) VALUES ('502100', 'M Quesadi Veg');
INSERT INTO productos (codigo, nombre) VALUES ('502136', 'M 3Tacos');
INSERT INTO productos (codigo, nombre) VALUES ('502138', 'M Bacon CH QU');
INSERT INTO productos (codigo, nombre) VALUES ('502170', 'M Burrito BC');
INSERT INTO productos (codigo, nombre) VALUES ('611004', 'CC 2 TacSupreme+ Bebida 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('611005', 'CC 2x1 Patatas Peque�as 4.00');
INSERT INTO productos (codigo, nombre) VALUES ('611006', 'CC 2x7 menus');
INSERT INTO productos (codigo, nombre) VALUES ('611007', 'CC Menu Cheesy Burrito 2.00');
INSERT INTO productos (codigo, nombre) VALUES ('611009', 'CC Menu Wrap Slider Carne 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('612002', 'CC Combo 2 Qrito+CrWrap 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('612007', 'CC Chicken Burrito + Pat 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('612009', 'CC Quesarito+ Patatas 2.00');
INSERT INTO productos (codigo, nombre) VALUES ('612010', 'CC Cr Wrap + Patatas 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('613005', 'CC GSB+Pat+Beb');
INSERT INTO productos (codigo, nombre) VALUES ('613006', 'CC M Chicken Burrito 2.00');
INSERT INTO productos (codigo, nombre) VALUES ('613007', 'CC M Quesadilla');
INSERT INTO productos (codigo, nombre) VALUES ('613008', 'CC M Quesarito');
INSERT INTO productos (codigo, nombre) VALUES ('750014', 'M Quesarito M');
INSERT INTO productos (codigo, nombre) VALUES ('750180', 'Box Griller P');
INSERT INTO productos (codigo, nombre) VALUES ('750185', 'Combo Griller M');
INSERT INTO productos (codigo, nombre) VALUES ('750188', 'Menu Griller P');
INSERT INTO productos (codigo, nombre) VALUES ('750189', 'Menu Griller M');
INSERT INTO productos (codigo, nombre) VALUES ('750197', 'Combo San Diego M');
INSERT INTO productos (codigo, nombre) VALUES ('750201', 'Menu San Diego M');
INSERT INTO productos (codigo, nombre) VALUES ('750203', 'Menu San Diego XG');
INSERT INTO productos (codigo, nombre) VALUES ('760002', 'Menu 3 Tacos Supreme 8.00');
INSERT INTO productos (codigo, nombre) VALUES ('760129', 'Men� Crunchy Wrap');
INSERT INTO productos (codigo, nombre) VALUES ('760130', 'Men� Quesarito');
INSERT INTO productos (codigo, nombre) VALUES ('760145', 'M Twins BC');
INSERT INTO productos (codigo, nombre) VALUES ('770101', 'Quesarito');
INSERT INTO productos (codigo, nombre) VALUES ('770105', 'Chicken Burrito');
INSERT INTO productos (codigo, nombre) VALUES ('770108', 'Twin BC');
INSERT INTO productos (codigo, nombre) VALUES ('770201', 'Quesadilla');
INSERT INTO productos (codigo, nombre) VALUES ('770204', 'Kidsadilla');
INSERT INTO productos (codigo, nombre) VALUES ('770205', 'Kidsadilla Queso');
INSERT INTO productos (codigo, nombre) VALUES ('770206', 'Bacon CH QU');
INSERT INTO productos (codigo, nombre) VALUES ('770409', 'BC Crunchy Wrap');
INSERT INTO productos (codigo, nombre) VALUES ('770501', 'Bacon Top Fries');
INSERT INTO productos (codigo, nombre) VALUES ('770510', 'Patatas Mexican');
INSERT INTO productos (codigo, nombre) VALUES ('770511', 'Nachos Con Queso');
INSERT INTO productos (codigo, nombre) VALUES ('770514', 'Nachos con Carne y Queso 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('771001', 'Menu Quesarito');
INSERT INTO productos (codigo, nombre) VALUES ('771003', 'Menu Gran Burrito');
INSERT INTO productos (codigo, nombre) VALUES ('771006', 'Menu Burrito Chicken 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('771007', 'Menu Crunchy Wrap');
INSERT INTO productos (codigo, nombre) VALUES ('771008', 'Menu Quesadilla');
INSERT INTO productos (codigo, nombre) VALUES ('771026', 'Menu Bacon CWrap BC 1.00');
INSERT INTO productos (codigo, nombre) VALUES ('780021', 'Pack 2 Personas');
INSERT INTO productos (codigo, nombre) VALUES ('780022', 'Pack 2 Personas');
INSERT INTO productos (codigo, nombre) VALUES ('900000', 'Sin');